apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: your-docker-registry/menu-image:latest  # 実際のイメージ名に置き換えてください
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
