apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: your-docker-registry/order-image:latest  # 実際のイメージ名に置き換えてください
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
